blank_issues_enabled: true
contact_links:
  - name: Problems With Twitch (aka not Extension stuff)
    url: https://help.twitch.tv/s/contactsupport
    about: We can't help you with Twitch Malarky so reach out to Twitch Support for help with that.
